import os
import json
from pathlib import Path

# Helper to read the JWT token used for authenticating API calls.
# The token is stored in data/jwt_token.txt when the system starts (generated by the auth flow).
# This utility is used by internal scripts (e.g., for curl commands) and can be imported by other modules.

def get_jwt_token() -> str:
    """Return the JWT token string.

    If the token file does not exist or is empty, raise a RuntimeError.
    """
    token_path = Path(__file__).resolve().parent.parent / "data" / "jwt_token.txt"
    if not token_path.is_file():
        raise RuntimeError(f"JWT token file not found at {token_path}")
    token = token_path.read_text().strip()
    if not token:
        raise RuntimeError("JWT token file is empty")
    return token
